# HiPerGator PRODUCTION profile
# Triggers archive_predictions.sh
executor: slurm
config:
  - "working_dir=/blue/ewhite/everglades"
  - "test=false"
latency-wait: 60
jobs: 20
keep-going: true
retries: 2
rerun-incomplete: true
use-conda: true
printshellcmds: true
default-resources:
  runtime: 60
  slurm_jobname: "smk.{rule}"
