executor: slurm
latency-wait: 60
jobs: 20
keep-going: true
rerun-incomplete: true
rerun-triggers:
  - mtime
use-conda: true
printshellcmds: true
default-resources:
  runtime: 60
  slurm_jobname: "smk.{rule}"
